### ISSUE TITLE
[WC 8.4] Programs filter drop-down is misaligned

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#2186]
### Describe the bug:

The single program filter in reports breaks the look of the dropdown

![image](https://github.com/woocommerce/google-listings-and-ads/assets/17435/e5403a88-e767-47ac-8909-180cb3362c62)

### Steps to reproduce:

1. Go to  **Marketing > GLA > Reports > Programs**
2. Click on the programs drop-down (Show:), pick "single program"
3. Type something to see the results

### Expected behavior:

No scrollbar should appear within the drop-down

### Actual behavior:

Input fields is wider that the dorn-down causing the scrollbars to appear.

### Additional details:

This may be just a WC components bug for `<ReportFilters>`, the following could help
```css
.woocommerce-filters-filter__search  > .woocommerce-select-control__control {
    box-sizing: border-box;
}
```
